/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeSearchRouteImport } from './routes/home/search'
import { Route as HomeProfileRouteImport } from './routes/home/profile'
import { Route as HomeMedicationsRouteImport } from './routes/home/medications'
import { Route as HomeAppointmentsRouteImport } from './routes/home/appointments'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeRoute,
} as any)
const HomeSearchRoute = HomeSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => HomeRoute,
} as any)
const HomeProfileRoute = HomeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => HomeRoute,
} as any)
const HomeMedicationsRoute = HomeMedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => HomeRoute,
} as any)
const HomeAppointmentsRoute = HomeAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => HomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/home/appointments': typeof HomeAppointmentsRoute
  '/home/medications': typeof HomeMedicationsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/search': typeof HomeSearchRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home/appointments': typeof HomeAppointmentsRoute
  '/home/medications': typeof HomeMedicationsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/search': typeof HomeSearchRoute
  '/home': typeof HomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteWithChildren
  '/home/appointments': typeof HomeAppointmentsRoute
  '/home/medications': typeof HomeMedicationsRoute
  '/home/profile': typeof HomeProfileRoute
  '/home/search': typeof HomeSearchRoute
  '/home/': typeof HomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/home/appointments'
    | '/home/medications'
    | '/home/profile'
    | '/home/search'
    | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home/appointments'
    | '/home/medications'
    | '/home/profile'
    | '/home/search'
    | '/home'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/home/appointments'
    | '/home/medications'
    | '/home/profile'
    | '/home/search'
    | '/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/search': {
      id: '/home/search'
      path: '/search'
      fullPath: '/home/search'
      preLoaderRoute: typeof HomeSearchRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/profile': {
      id: '/home/profile'
      path: '/profile'
      fullPath: '/home/profile'
      preLoaderRoute: typeof HomeProfileRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/medications': {
      id: '/home/medications'
      path: '/medications'
      fullPath: '/home/medications'
      preLoaderRoute: typeof HomeMedicationsRouteImport
      parentRoute: typeof HomeRoute
    }
    '/home/appointments': {
      id: '/home/appointments'
      path: '/appointments'
      fullPath: '/home/appointments'
      preLoaderRoute: typeof HomeAppointmentsRouteImport
      parentRoute: typeof HomeRoute
    }
  }
}

interface HomeRouteChildren {
  HomeAppointmentsRoute: typeof HomeAppointmentsRoute
  HomeMedicationsRoute: typeof HomeMedicationsRoute
  HomeProfileRoute: typeof HomeProfileRoute
  HomeSearchRoute: typeof HomeSearchRoute
  HomeIndexRoute: typeof HomeIndexRoute
}

const HomeRouteChildren: HomeRouteChildren = {
  HomeAppointmentsRoute: HomeAppointmentsRoute,
  HomeMedicationsRoute: HomeMedicationsRoute,
  HomeProfileRoute: HomeProfileRoute,
  HomeSearchRoute: HomeSearchRoute,
  HomeIndexRoute: HomeIndexRoute,
}

const HomeRouteWithChildren = HomeRoute._addFileChildren(HomeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
